### ISSUE TITLE
Add cabal.config link to snapshot pages

### ISSUE THREAD

**Issue by fgaz** [fpco/stackage-server#232] opened 2017-07-22 14:19 UTC
As the title says, I propose to restore the link to the `cabal.config` file in the snapshot pages.
It doesn't take much space (you can even hide it under a "+", just tell me if you want a pr for it), and it's one of the two ways to use Stackage (more so, it's the original one!).

I'm sure it will be useful to many. I only knew about that file because I already used it when the link was there, but probably a lot of people don't realize it's even available (it's an orphan page).

All it takes is a `git revert` e0f8755.

**Comment by hvr** [comment] 2017-07-22 18:51
See also https://github.com/fpco/stackage-server/issues/171#issuecomment-242982951

**Comment by fgaz** [comment] 2017-09-03 20:55
Any news?

**Comment by snoyberg** [comment] 2017-09-04 08:48
Just chatted with Chris about this. We removed the link originally because it was causing user confusion with uncertainty on how to get started with Stackage. As users standardized on the Stack+Stackage workflow, it made sense to avoid the confusion.

I'm not opposed to adding in information on using with cabal-install again, but in its current state, I don't believe we can advertise the cabal.config file. In particular, due to Hackage file revisions sometimes breaking old build plans, the current format (which does not include any Hackage file revision information) in unsuitable. I'm not familiar with all the details of cabal.config files to know if they support indicating Hackage file revisions. Such a change would be necessary to reliably provide support for cabal-install.

**Comment by fgaz** [comment] 2017-09-04 12:24
`--index-state` can do it. Just make the instructions like this:

```
wget https://www.stackage.org/$snapshot/cabal.config
cabal whatever --index-state=$snapshot_date
```

**Comment by DanBurton** [comment] 2017-09-04 15:25
`cabal` has gained a feature called `--index-state` which allows you to interact with the entire package index as though it were `$snapshot_date` (meaning: without any new versions or revisions that occur after that date). So as long as the cabal.config that we publish works on `$snapshot_date`, we just also publish the date, and users can use this technique to guarantee consistent builds, even despite changes to the package index on later dates.

I'm not convinced that this is a good workflow, though. If users want to add any packages outside of the snapshot, it will be confusing to them why outside packages are also arbitrarily constrained to old versions.

**Comment by fgaz** [comment] 2017-09-04 16:37
I don't really see a problem with the revisions because
1. They are designed to _not_ break anything when used correctly (which is fairly easy to do).
0. Anedoctally, they _do not_ break things in 99% of cases.
0. If you are entrusting your deps' developers with running code on your sistem you should trust them to mantain correct revisions too.

In the improbable case that incorrect revisions break things, an user can fall back on the `--index-state` method until they are corrected (or permanently).

In light of this, here's my suggestion for the cabal guide:

> [+ cabal-install guide]
> ↑ when clicked will expand the section
>
> _[BIG SCARY RED WARNING ABOUT HOW THIS METHOD IS NOT SUPPORTED BY FPCOMPLETE]_
>
> `wget https://www.stackage.org/$snapshot/cabal.config`
> `cabal whatever`
> This should work in most of cases. If it fails with a [check what error it is], there is a chance that the error is caused by incorrect revisions.
> In this case, you can try:
> cabal whatever --index-state=$snapshot_date
> If the problem is fixed by the --index-state flag [link to what it does], you should report the revision problem to the author of the offending package.
> You can also use `--index-state` to ensure that your install plan will never change.
> N.B.: `--index-state` will also constrain all your other dependencies to versions before the date blah blah blah...

**Comment by snoyberg** [comment] 2017-09-05 04:26
The fact is that Hackage revisions _have_ broken snapshots in the past, this isn't a theoretical discussion. And the point of Stackage is to give guarantees about build plans, which currently can only be done through Stack (unless someone wants to PR the cabal.config files we generate to include the Hackage file revision info).

To reiterate: there are two different issues here:

* Confusing users about how to get started. We're recommending they get started with Stack, because it works reliably. We are _not_ recommending they use cabal, since it does not have first class support for Stackage, or even correct support in the presence of Hackage revisions
* If we include this information and people have a negative experience, it will reflect badly on Stackage and/or cause maintenance overhead for the Stackage Curator team

> If you are entrusting your deps' developers with running code on your sistem you should trust them to mantain correct revisions too.

The issue is that maintaining revisions that don't break a snapshot is a tricky job, and people make mistakes. Additionally, it's not just the developers themselves; Hackage Trustees can add overly restrictive bounds that break snapshots too.

**Comment by snoyberg** [comment] 2017-12-20 04:46
I've added a warning about the lack of support for revisions in cabal.config in f9632d734c1ddb05f90ecdb8f91dfd66cef03602. Closing.

**Closed by snoyberg** 2017-12-20 04:46 UTC

**Comment by bsima** [comment] 2018-04-18 16:42
For reference to anyone googling this, cabal.config files can be found at an address like `https://www.stackage.org/lts-9.21/cabal.config`

(I hope this continues to be published, I find it very useful.)
