### ISSUE TITLE
foldr in base appears on page 4 of Hoogle

### ISSUE THREAD

**Issue by tomjaguarpaw** [fpco/stackage-server#186] opened 2016-06-20 07:06 UTC
Currently I have to scroll to page 4 before I find the definition of `foldr` from `base`.  It should be the first result!

https://www.stackage.org/lts-6.3/hoogle?q=foldr&page=4

**Comment by chrisdone** [comment] 2016-07-15 17:04
Thanks for the report, this is an artifact of upgrading to hoogle 5, I'm not sure what's causing this ordering at the moment.

**Comment by chrisdone** [comment] 2016-07-15 17:05
Closing as dupe of #183. Bump again if I've misjudged.

**Closed by chrisdone** 2016-07-15 17:05 UTC
Labels: bug
